export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";

export const START_PRODUCTS_DOWNLOAD = "START_PRODUCT_DOWNLOAD";
export const PRODUCTS_DONWLOAD_SUCCESS = "PRODUCTS_DONWLOAD_SUCCESS";
export const PRODUCTS_DONWLOAD_ERROR = "PRODUCTS_DONWLOAD_ERROR";

export const INIT_PRODUCT_ELIMINATE = "INIT_PRODUCT_ELIMINATE";
export const PRODUCT_ELIMINATED_SUCCESS = "PRODUCT_ELIMINATED_SUCCESS";
export const PRODUCT_ELIMINATED_ERROR = "PRODUCT_ELIMINATED_ERROR";

export const GET_EDIT_PRODUCT = "GET_EDIT_PRODUCT";
export const INIT_EDIT_PRODUCT = "INIT_EDIT_PRODUCT";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_ERROR = "EDIT_PRODUCT_ERROR";
